// <auto-generated />
using MVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCData.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20220214170916_AdditionalSeedDataAdded")]
    partial class AdditionalSeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCData.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("Stad")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Namn")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("Telefonnummer")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            City = "TestCity1",
                            Name = "TestPerson1",
                            PhoneNumber = "001234567"
                        },
                        new
                        {
                            PersonId = 2,
                            City = "TestCity2",
                            Name = "TestPerson2",
                            PhoneNumber = "003554321"
                        },
                        new
                        {
                            PersonId = 3,
                            City = "TestCity3",
                            Name = "TestPerson3",
                            PhoneNumber = "004466732"
                        },
                        new
                        {
                            PersonId = 4,
                            City = "TestCity4",
                            Name = "TestPerson4",
                            PhoneNumber = "0068995543"
                        },
                        new
                        {
                            PersonId = 5,
                            City = "TestCity5",
                            Name = "TestPerson5",
                            PhoneNumber = "00356446794"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
